[tool.poetry]
name = "FloatDelDot"
version = "1.1.6"
description = "This prorgamm delete dot in float (15.0 -> 15)"
authors = ["GleDVIn <gledvin.info@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
