[tool.poetry]
name = "wf-airtable-api-client"
version = "1.2.1"
description = "WF Airtable API client"
authors = ["Benjamin Jaffe-Talberg <ben.talberg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
wf-airtable-api-schema = "^0.3.0"

[tool.poetry.dev-dependencies]
autopep8 = '>=1.5.5'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 1