[tool.poetry]
name = "zohavi"
version = "0.1.12"
description = ""
authors = ["pub12 <pubudu79@gmail.com>"]
#packages = [ 
#                { include = "zbase" },
#                { include = "zcommon" },
#            ]

            
[tool.poetry.dependencies]
python = "^3.8"
 
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
