[tool.poetry]
name = "dsci_prediction"
version = "4"
description = "a package for predicting if cancer is treatable or not"
authors = ["Clichy Bazenga"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
