[tool.poetry]
name = "eth-sdk"
version = "0.0.2"
description = "SDK to interact with EVM compatible blockchains"
authors = ["Arugulo <arugulo@protonmail.com>"]
license = "MIT"

[tool.poetry.scripts]
eth-sdk = "eth_sdk.shell:cli"

[tool.poetry.dependencies]
python = "^3.7.2"
web3 = "^5.24.0"
click = "7.1.1"
PyYAML = "^6.0"
requests = "^2.26.0"
dotsi = "^0.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
