[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qade"
version = "0.1.2"
description = "Differential equation solving through quantum annealing"
authors = [{name ="Juan Carlos Criado"}, {name = "Michael Spannowsky"}]
keywords = ["differential equations", "quantum annealing"]
license = {file = "LICENSE.txt"}
classifiers = ["Programming Language :: Python :: 3",]
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["dwave-ocean-sdk", "numpy>=1.20"]

[tool.setuptools]
packages = ["qade"]
