[tool.poetry]
name = "eHelply-Microservice-Library"
version = "1.7.16"
description = ""
authors = ["Shawn Clake <shawn.clake@gmail.com>"]
readme = "readme.md"
homepage = "https://ehelply.com"

[tool.poetry.dependencies]
python = "~3.8"
ehelply-bootstrapper = "^0.15.0"
ehelply-generator = "^0.1.2"
ehelply-updater = "^0.1.5"
ehelply-python-sdk = "^0.2.8"
jinja2 = "^2.11.3"
pytest-mock = "^3.6.1"

[tool.poetry.scripts]
ehelply_microservice_library = 'ehelply_microservice_library.cli.self_cli:cli_main'

[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
